### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by jessejanderson** [dvcrn/proton#156]
Not sure what's going on - now getting this error on every launch, gets stuck with the Proton modal up at "Initializing proton... Just a moment!"

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2008

TypeError: Cannot read property '0' of null
    at cljs.reader.read_keyword (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2575:161)
    at Object.cljs.reader.read_delimited_list (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2563:74)
    at cljs.reader.read_map (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2567:142)
    at Object.cljs.reader.read_delimited_list (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2563:74)
    at cljs.reader.read_map (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2567:142)
    at Object.cljs.reader.read [as read] (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2584:72)
    at Object.cljs.reader.read_string (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2584:368)
    at Object.proton.lib.proton.load_config (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2612:163)
    at /Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2975:21
    at d (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2972:199)
    at b (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2973:17)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2007:198)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:2008:116)
    at /Users/Jesse/.atom/packages/proton-mode/lib/proton.js:3002:408
    at Immediate.cljs.core.async.impl.dispatch.process_messages [as _onImmediate] (/Users/Jesse/.atom/packages/proton-mode/lib/proton.js:1964:298)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-jshint",
      "vim-mode-plus",
      "atom-alignment",
      "tabs"
    ],
    "themes": [
      "isotope-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.11.0
aligner, v0.19.1
atom-ternjs, v0.13.2
atomatigit, v1.5.5
autoclose-html, v0.21.0
autocomplete-elixir, v1.5.13
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
autoupdate-packages, v1.3.1
chester-atom-syntax, v0.1.1
css-snippets, v0.9.0
docblockr, v0.7.3
easy-motion-redux, v1.0.0
emmet, v2.4.1
environment, v1.1.1
file-icons, v1.6.14
highlight-line, v0.11.1
iex, v0.9.27
indent-guide-improved, v1.4.5
isotope-ui, v2.7.1
javascript-snippets, v1.2.1
language-diff, v0.4.0
language-elixir, v0.11.1
language-haml, v0.23.15
language-slim, v0.5.0
linter, v1.11.3
linter-bootlint, v1.0.0
linter-clojure, v1.1.2
linter-csslint, v1.3.1
linter-elixirc, v1.1.5
linter-eslint, v6.0.0
linter-haml, v1.1.0
linter-rubocop, v0.4.7
linter-sass-lint, v1.1.0
linter-slim, v1.0.0
linter-xmllint, v1.3.3
markdown-scroll-sync, v2.1.2
minimap, v4.19.0
pigments, v0.24.1
project-manager, v2.7.6
proton-mode, v0.8.0
react, v0.14.1
react-snippets, v0.3.0
recent-files-fuzzy-finder, v0.2.4
relative-numbers, v0.5.0
release-notes, v0.53.0
terminal-plus, v0.14.5
vim-mode, v0.64.0
vim-surround, v0.8.1
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by dvcrn** [comment]
Can you post your .proton config if possible?

**Comment by jessejanderson** [comment]
Found my issue, I'd added `:/ {:action "fuzzy-grep:toggle"}` to my .proton keybindings.

Is there a trick to mapping `SPC /` in my .proton?

**Comment by dvcrn** [comment]
Ok so the problem here is that `:/` is not a valid keyword. What we did inside proton core is, we used `(keyword "/")` to generate the keyword but that's closure and not edn. I'll try to think about something to make this work
