### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by raguay** [dvcrn/proton#2]
Hi,

I am getting this error when atom starts:

TypeError: Cannot read property 'addBottomPanel' of null
    at Object.<anonymous> (/Users/raguay/Documents/proton/plugin/lib/proton.js:1806:80)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:192:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)

**Comment by dvcrn** [comment]
Hi,

Can you try typing `atom.workspace` inside the dev tools and see what you get back? 

Also can I ask how you found this project? Stars jumped from 1 to 18 in a few hours and I'm a bit confused how :p

**Comment by raguay** [comment]
Hi,

The jump in numbers was due to a tweet on twitter about this project. I was able to get it working by updating Atom. I did not realize that my Atom was behind in an update. But, a sample .proton file would be nice as I am not sure what should go in it. How close to my .spacemacs file would it be? I assume quit a bit different.

**Comment by dvcrn** [comment]
The current .proton file looks like this: https://github.com/dvcrn/proton/blob/master/templates/proton.edn the layout is not frozen yet so if you have a cool idea definitely let me know!

The idea is also that we create this file for the user if he doesn't have one but I couldn't find time to do that yet.

**Comment by raguay** [comment]
Okay. Thanks. I will be looking at this.

Richard
