### ISSUE TITLE
Uncaught TypeError: a.call is not a function

### ISSUE THREAD

**Issue by benwbooth** [dvcrn/proton#207]
[Enter steps to reproduce below:]

1. Install Atom 1.8.0
2. rm -rf ~/.atom
3. apm install proton-mode
4. open any file
5. hit space bar

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package, v0.10.1

### Stack Trace

Uncaught TypeError: a.call is not a function

```
At /Users/ben/.atom/packages/proton-mode/lib/proton.js:2381

TypeError: a.call is not a function
    at proton.lib.helpers.show_item_QMARK_ (/Users/ben/.atom/packages/proton-mode/lib/proton.js:2381:374)
    at /Users/ben/.atom/packages/proton-mode/lib/proton.js:918:277
    at [object Object].cljs.core.LazySeq.sval (/Users/ben/.atom/packages/proton-mode/lib/proton.js:610:253)
    at [object Object].cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/ben/.atom/packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/Users/ben/.atom/packages/proton-mode/lib/proton.js:355:142)
    at /Users/ben/.atom/packages/proton-mode/lib/proton.js:873:120
    at [object Object].cljs.core.LazySeq.sval (/Users/ben/.atom/packages/proton-mode/lib/proton.js:610:253)
    at [object Object].cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/ben/.atom/packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/Users/ben/.atom/packages/proton-mode/lib/proton.js:355:142)
    at Function.clojure.string.join.cljs$core$IFn$_invoke$arity$2 (/Users/ben/.atom/packages/proton-mode/lib/proton.js:1870:344)
    at Object.proton.lib.helpers.tree__GT_html (/Users/ben/.atom/packages/proton-mode/lib/proton.js:2384:521)
    at Object.proton.core.on_space (/Users/ben/.atom/packages/proton-mode/lib/proton.js:3063:301)
    at atom-workspace.proton.core.toggle (/Users/ben/.atom/packages/proton-mode/lib/proton.js:3067:227)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:28.7.0 vim-mode-plus:start-move-to-mark-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:27.9.0 editor:newline (atom-text-editor.vim-mode-plus-input-char-waiting)
     -0:25.2.0 editor:consolidate-selections (atom-text-editor.vim-mode-plus-input-char-waiting)
     -0:25.2.0 core:cancel (atom-text-editor.vim-mode-plus-input-char-waiting)
     -0:24.2.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:22.6.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode.autocomplete-active)
  2x -0:22.4.0 vim-mode-plus:undo (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  3x -0:17.6.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:17.1.0 proton:toggle (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  4x -0:15.7.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:14 proton:toggle (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:13.6.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:13.4.0 proton:toggle (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:13.1.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
 17x -0:09.6.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.8.0 proton:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.3
atom-dark-fusion-syntax, v1.1.0
autocomplete-paths, v1.0.2
autoupdate-packages, v1.3.1
easy-motion-redux, v1.1.1
environment, v1.2.0
file-icons, v1.7.15
highlight-line, v0.11.1
highlight-selected, v0.11.2
nucleus-dark-ui, v0.8.6
project-plus, v0.9.0
proton-mode, v0.10.1
recent-files-fuzzy-finder, v0.2.4
relative-numbers, v0.5.1
release-notes, v0.53.0
tab-switcher, v1.5.3
vim-mode-plus, v0.46.0
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by benwbooth** [comment]
Also happens with proton mode built from git master

**Comment by geksilla** [comment]
@benwbooth, did you customize `.proton` file or used default?

**Comment by benwbooth** [comment]
@geksilla I don't have a ~/.proton file.

**Comment by dvcrn** [comment]
@benwbooth proton should automatically create one for you if you don't have one.

If you have time, could you try to build proton from source here and see if the latest version fixes your problems?

**Comment by benwbooth** [comment]
@dvcm it did indeed create a .proton file for me. I did not make any changes to it.

I tried re-installing proton from git master, and I'm still getting the same error when pressing the space bar. It seems to go into insert mode, then the error message `Uncaught TypeError: a.call is not a function` pops up.

**Comment by benwbooth** [comment]
I've also tried it on my home computer (also macOS)  with the same results.

**Comment by vimuel** [comment]
Hi, having the exact same issue. Any ideas what I could try?

**Comment by dvcrn** [comment]
@vimuel did you also try the latest develop branch? 

I wasn't able to reproduce this problem yet, how about you @geksilla? Any luck?

**Comment by geksilla** [comment]
Yes, I've reproduced this issue.
Remove `~/.proton`, wait until setup complete, hit `spc` and error appears in dev console. However after editor refresh issue is gone. Error thrown on [this line](https://github.com/dvcrn/proton/blob/master/src/cljs/proton/lib/helpers.cljs#L93). Seems like `options` is *undefined* or *null* in some case.

**Comment by benwbooth** [comment]
I can no longer reproduce this bug in the latest version of Proton mode. It's working now!

**Comment by dvcrn** [comment]
Interesting. I'm closing this then until the bug re-surfaces

**Comment by aislanmaia** [comment]
After update the .proton file and add some layers, when toggling the proton-mode the "Uncaught TypeError: a.call is not a function" happens.
