### ISSUE TITLE
SPC creates Uncaught TypeError

### ISSUE THREAD

**Issue by bobbywlindsey** [dvcrn/proton#242]
# Steps to Reproduce

1. fresh install of Atom for MacOS
2. immediately installed proton
3. once installed, I opened a JavaScript file, pressed the spacebar to get menu options and was greeted with an uncaught type error (this happens with other filetypes as well)

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package, v0.13.0

### Stack Trace

Uncaught TypeError: a.call is not a function

```
At /Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:2383

TypeError: a.call is not a function
    at proton.lib.helpers.show_item_QMARK_ (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:2383:374)
    at /Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:918:277
    at cljs.core.LazySeq.sval (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:610:253)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:355:142)
    at /Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:873:120
    at cljs.core.LazySeq.sval (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:610:253)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:355:142)
    at Function.clojure.string.join.cljs$core$IFn$_invoke$arity$2 (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:1872:344)
    at Object.proton.lib.helpers.tree__GT_html (/Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:2386:521)
    at /Users/bobbylindsey/.atom/packages/proton-mode/lib/proton.js:3099:477
```

### Commands

```
     -2:07.6.0 proton:chain (atom-text-editor.editor.is-focused.normal-mode)
     -2:07.2.0 proton:toggle (atom-text-editor.editor.is-focused.normal-mode.vim-mode-plus)
     -2:07.1.0 proton:chain (atom-text-editor.editor.is-focused.normal-mode)
     -2:05.6.0 vim-mode-plus:find (atom-text-editor.editor.is-focused.normal-mode.vim-mode-plus)
     -2:04.7.0 editor:consolidate-selections (atom-text-editor.vim-mode-plus-input-char-waiting.is-focused.find-pending)
     -2:04.7.0 core:cancel (atom-text-editor.vim-mode-plus-input-char-waiting.is-focused.find-pending)
  2x -2:04.0 vim-mode-plus:move-down (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
  3x -2:03.8.0 vim-mode-plus:move-up (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
  6x -2:01.5.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
  8x -1:56.7.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
     -1:12.4.0 proton:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  7x -1:08.8.0 blur (atom-text-editor.editor.normal-mode.is-focused)
     -0:03.3.0 proton:chain (atom-text-editor.editor.normal-mode.is-focused)
     -0:02.3.0 vim-mode-plus:move-down (atom-text-editor.editor.normal-mode.is-focused.vim-mode-plus)
     -0:02.1.0 vim-mode-plus:move-up (atom-text-editor.editor.normal-mode.is-focused.vim-mode-plus)
     -0:00.4.0 proton:toggle (atom-text-editor.editor.normal-mode.is-focused.vim-mode-plus)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "tabs"
    ],
    "telemetryConsent": "no",
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-dark-fusion-syntax, v1.3.2 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
autocomplete-paths, v1.0.2 (active)
autoupdate-packages, v1.3.1 (active)
busy, v0.7.0 (active)
easy-motion-redux, v1.1.1 (active)
environment, v1.3.1 (active)
ex-mode, v0.13.0 (inactive)
expand-region, v0.2.5 (inactive)
file-icons, v1.7.23 (active)
golden-ratio, v0.3.0 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
lines, v0.13.1 (inactive)
maximize-panes, v0.2.0 (inactive)
move-panes, v0.2.0 (inactive)
nucleus-dark-ui, v0.10.12 (active)
project-plus, v0.9.0 (active)
proton-mode, v0.13.0 (active)
recent-files-fuzzy-finder, v0.2.4 (active)
relative-numbers, v0.5.1 (active)
release-notes, v0.53.0 (active)
tab-switcher, v1.5.4 (active)
theme-switch, v0.4.0 (inactive)
vim-mode-plus, v0.63.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (active)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by bobbywlindsey** [comment]
I uninstalled the proton package then reinstalled it. Looks like that fixed the space bar issue.

**Comment by benjamin-rood** [comment]
I'm having this same problem, both on macOS and Linux (Pop!_OS 18.04 LTS). Both fresh installs, only package installed was Proton Mode via `apm install proton-mode`

Uninstalling the packing using the package manager inside Atom and re-installing it now means that the 
menu by <kbd>SPC</kbd> works, but it now throws another instead.

@dvcrn David, should I open a new issue?
