### ISSUE TITLE
Uncaught TypeError: a.call is not a function

### ISSUE THREAD

**Issue by aikeru** [dvcrn/proton#258]
1. Install fresh copy of atom.io
2. Install fresh copy of proton
3. Wait until install completes and before doing anything else, hit "space" on the open editor window
4. See exception :)

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package 0.14.1

### Stack Trace

Uncaught TypeError: a.call is not a function

```
At C:\Users\micha\.atom\packages\proton-mode\lib\proton.js:2383

TypeError: a.call is not a function
    at proton.lib.helpers.show_item_QMARK_ (/packages/proton-mode/lib/proton.js:2383:374)
    at /packages/proton-mode/lib/proton.js:918:277
    at cljs.core.LazySeq.sval (/packages/proton-mode/lib/proton.js:610:253)
    at /packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/packages/proton-mode/lib/proton.js:355:142)
    at /packages/proton-mode/lib/proton.js:873:120
    at cljs.core.LazySeq.sval (/packages/proton-mode/lib/proton.js:610:253)
    at /packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/packages/proton-mode/lib/proton.js:355:142)
    at /packages/proton-mode/lib/proton.js:1872:344)
    at Object.proton.lib.helpers.tree__GT_html (/packages/proton-mode/lib/proton.js:2386:521)
    at /packages/proton-mode/lib/proton.js:3107:477
```

### Commands

```
     -4:42 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-one-dark-syntax.theme-one-dark-ui.theme-atom-material-ui.theme-nucleus-dark-ui.theme-atom-dark-fusion-syntax.theme-atom-material-syntax)
     -0:13 proton:toggle (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
atom-dark-fusion-syntax 2.0.3 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocomplete-paths 1.0.5 
autoupdate-packages 1.3.1 
busy 0.7.0 
easy-motion-redux 1.1.1 
environment 1.3.1 
ex-mode 0.13.1 
expand-region 0.2.6 
file-icons 2.0.16 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.12.0 
lines 0.13.1 
maximize-panes 0.2.0 
move-panes 0.2.0 
nucleus-dark-ui 0.11.0 
project-plus 0.9.0 
proton-mode 0.14.1 
recent-files-fuzzy-finder 0.3.0 
relative-numbers 0.7.1 
release-notes 0.53.0 
tab-switcher 1.5.4 
theme-switch 0.4.0 
vim-mode-plus 0.82.3 
vim-mode-plus-ex-mode 0.9.0 
zentabs 0.8.8 
```

**Comment by aikeru** [comment]
Reopened atom.io immediately after this and noticed proton installing more stuff... (7 new packages)

**Comment by aikeru** [comment]
Looks like things are working after that last bit... Hope this is helpful
