### ISSUE TITLE
Pressing spacebar after a fresh install throws an error

### ISSUE THREAD

**Issue by sfalcon** [dvcrn/proton#277]
1. Install fresh Atom
2. Install proton-mode package from inside Atom
3. Wait for setup to complete
4. Press spacebar for bang

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package 0.16.0

### Stack Trace

Uncaught TypeError: a.call is not a function

```
At /Users/SamFalcon/.atom/packages/proton-mode/lib/proton.js:2383

TypeError: a.call is not a function
    at proton.lib.helpers.show_item_QMARK_ (/packages/proton-mode/lib/proton.js:2383:374)
    at /packages/proton-mode/lib/proton.js:918:277
    at cljs.core.LazySeq.sval (/packages/proton-mode/lib/proton.js:610:253)
    at /packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/packages/proton-mode/lib/proton.js:355:142)
    at /packages/proton-mode/lib/proton.js:873:120
    at cljs.core.LazySeq.sval (/packages/proton-mode/lib/proton.js:610:253)
    at /packages/proton-mode/lib/proton.js:613:233)
    at Object.cljs.core.seq (/packages/proton-mode/lib/proton.js:355:142)
    at /packages/proton-mode/lib/proton.js:1872:344)
    at Object.proton.lib.helpers.tree__GT_html (/packages/proton-mode/lib/proton.js:2386:521)
    at /packages/proton-mode/lib/proton.js:3114:477
```

### Commands

```
     -8:24.5.0 settings-view:install-packages-and-themes (atom-pane.pane.active)
     -8:14.2.0 core:confirm (input.hidden-input)
     -4:04.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.theme-atom-material-ui.theme-nucleus-dark-ui.theme-atom-dark-fusion-syntax.theme-atom-material-syntax)
     -0:17.3.0 proton:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-nucleus-dark-ui)
     -0:06.1.0 proton:chain (div.panels-item)
     -0:02.0 proton:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.4 
atom-dark-fusion-syntax 2.2.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-paths 1.0.5 
autoupdate-packages 1.3.1 
busy 0.7.0 
easy-motion-redux 1.1.1 
ex-mode 0.17.0 
expand-region 0.3.1 
file-icons 2.1.9 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
lines 0.13.1 
maximize-panes 0.2.0 
move-panes 0.2.0 
nucleus-dark-ui 0.12.3 
project-plus 1.0.0 
proton-mode 0.16.0 
recent-files-fuzzy-finder 0.3.2 
relative-numbers 0.8.0 
release-notes 0.53.0 
tab-switcher 1.5.4 
theme-switch 0.4.0 
vim-mode-plus 0.96.2 
zentabs 0.8.8 
```

**Comment by sfalcon** [comment]
I restarted the App and it started working, but it was weird :)
