### ISSUE TITLE
SPC menu uncaught TypeError: 'nodeName'

### ISSUE THREAD

**Issue by benjamin-rood** [dvcrn/proton#300]
[Enter steps to reproduce:]

1. Press <kbd>SPC</kbd>

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Pop!_OS 18.04
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package 0.16.0

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.t.exports.CommandLogger.logCommand (/usr/share/atom/resources/app/static/<embedded>:11:895565)
    at /usr/share/atom/resources/app/static/<embedded>:11:894887
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349687)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348530)
    at Object.proton.lib.atom.eval_action_BANG_ (/packages/proton-mode/lib/proton.js:2447:29)
    at Object.proton.lib.keymap.exec_binding (/packages/proton-mode/lib/proton.js:2485:513)
    at HTMLElement.proton.core.chain (/packages/proton-mode/lib/proton.js:3074:346)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230760)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226894)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:285234)
```

### Commands

```
     -6:41.6.0 proton:toggle (atom-pane.pane.active)
     -4:20.7.0 proton:chain (input.hidden-input)
 12x -3:52 core:move-left (input.hidden-input)
  2x -3:30.7.0 core:move-up (div.panels-item)
  3x -3:26.9.0 core:move-down (div.panels-item)
     -3:26.9.0 core:move-up (div.panels-item)
     -1:13.6.0 proton:toggle (div.panels-item)
     -1:11.1.0 proton:chain (div.panels-item)
     -1:07.4.0 proton:toggle (div.panels-item)
     -0:11.6.0 proton:chain (div.panels-item)
     -0:10.9.0 proton:toggle (div.panels-item)
     -0:10.7.0 proton:chain (div.panels-item)
     -0:09.4.0 proton:toggle (div.panels-item)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-dark-fusion-syntax 2.2.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atomatigit 1.5.5 
autocomplete-paths 2.12.2 
autoupdate-packages 1.3.1 
blame 1.1.0 
busy 0.7.0 
busy-signal 2.0.0 
easy-motion-redux 1.3.3 
ex-mode 0.18.0 
expand-region 0.4.2 
file-icons 2.1.29 
git-history 3.3.0 
git-plus 8.4.2 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.14.0 
intentions 1.1.5 
language-diff 0.7.0 
lines 0.13.1 
linter 2.3.0 
linter-ui-default 1.7.1 
maximize-panes 0.2.0 
merge-conflicts 1.4.5 
move-panes 0.2.0 
nucleus-dark-ui 0.12.3 
project-plus 1.0.0 
proto-repl 1.4.24 
proton-mode 0.16.0 
recent-files-fuzzy-finder 0.6.1 
relative-numbers 0.9.0 
release-notes 0.53.0 
tab-switcher 1.5.6 
theme-switch 0.6.0 
vim-mode-plus 1.36.0 
zentabs 0.8.9 
```

**Comment by dvcrn** [comment]
Thanks for the report! I'll try to take a look at it but currently don't have much time I can put into this project. If you can, try compiling from source and adding debug output at the places mentioned in the stacktrace, that should shed some more light into what's wrong
