### ISSUE TITLE
Proton Throws on installation 

### ISSUE THREAD

**Issue by ticviking** [dvcrn/proton#70]
The existence of proton convinced me to give Atom a try, I just downloaded the latest atom, and tried to install proton. I receive the following error report any time I try to start atom. It looks to me like some part of proton's config process is failing, but I'm not sure where to start debugging.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [proton-mode](https://github.com/dvcrn/proton-bin) package, v0.3.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, write

```
At C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2132

Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:663:20)
    at SyncWriteStream.write (fs.js:1981:6)
    at Object.execSync (child_process.js:491:20)
    at Object.proton.lib.proton.create_default_config_BANG_ (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2003:284)
    at Object.proton.lib.proton.load_config (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2004:114)
    at C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2610:410
    at d (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2608:164)
    at b (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2609:17)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2131:198)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2132:116)
    at C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2635:153
    at Immediate.cljs.core.async.impl.dispatch.process_messages [as _onImmediate] (C:\Users\awh\.atom\packages\proton-mode\lib\proton.js:2088:298)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
proton-mode, v0.3.0

# Dev
No dev packages
```

**Comment by geksilla** [comment]
Seems like proton can't create `.proton` because of permissions. Quick workaround is you can create it by your own in `~/.proton` for linux or in your `C:\Users\USER_NAME\.proton` folder and copy paste content from [default template](https://raw.githubusercontent.com/dvcrn/proton/master/plugin/templates/proton.edn).

**Comment by dvcrn** [comment]
@ticviking just to make sure, did manually copying the template solve this for you?

**Comment by ticviking** [comment]
It does not seem to have.

It seems that somehow read only is being set for `c:\Users\$USER_NAME\.proton` when I launch atom. 

I can't poke at it much until after new year, but I'm happy to try anything that might figure out if this is a problem with proton or atom, or my system.
